export const SET_SELECTED_RACE = "SET_SELECTED_RACE";
export const SET_SELECTED_CLASS = "SET_SELECTED_CLASS";
export const SET_ABILITY_SCORE_ASSIGNMENTS = "SET_ABILITY_SCORE_ASSIGNMENTS";
export const SET_CAN_CONTINUE = "SET_CAN_CONTINUE";
export const SET_BUILD_STAGE = "SET_BUILD_STAGE";
